# Copyright Utah State University Research Foundation.
# All rights reserved except as specified below.
# This information is protected by a Non-Disclosure/Government Purpose
# License Agreement and is authorized only for United States Federal
# Government use.
# This information may be subject to export control.

[tool.black]
line-length = 80
